# Generated by Django 5.2.17 on 2026-09-23 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioORM',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios_usuario',
            },
        ),
        migrations.CreateModel(
            name='AdministradorORM',
            fields=[
                ('usuarioorm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuarioorm')),
            ],
            options={
                'db_table': 'usuarios_administrador',
            },
            bases=('usuarios.usuarioorm',),
        ),
        migrations.CreateModel(
            name='VendedorORM',
            fields=[
                ('usuarioorm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuarioorm')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='usuarios.administradororm')),
            ],
            options={
                'db_table': 'usuarios_vendedor',
            },
            bases=('usuarios.usuarioorm',),
        ),
    ]
