# Generated by Django 5.2.17 on 2026-09-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioorm',
            name='activo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
