"""Módulo Domain - Todos los dominios"""

from core.domain.producto import (
    Producto,
    ProductoId,
    NombreProducto,
    Precio,
    Cantidad,
    StockMinimo,
    EstadoStock,
    ProductoIdInvalidoException,
    NombreProductoInvalidoException,
    CategoriaInvalidaException,
    PrecioInvalidoException,
    CantidadInvalidaException,
    StockMinimoInvalidoException,
    ProductoNoEncontradoException,
    ProductoDuplicadoException,
    StockInsuficienteException,
    ProductoInactivoException,
    StockPorDebajoDelMinimoException,
    CategoriaVaciaException,
    ProductoRepository,
)

__all__ = [
    'Producto',
    'ProductoId',
    'NombreProducto',
    'Precio',
    'Cantidad',
    'StockMinimo',
    'EstadoStock',
    'ProductoIdInvalidoException',
    'NombreProductoInvalidoException',
    'CategoriaInvalidaException',
    'PrecioInvalidoException',
    'CantidadInvalidaException',
    'StockMinimoInvalidoException',
    'ProductoNoEncontradoException',
    'ProductoDuplicadoException',
    'StockInsuficienteException',
    'ProductoInactivoException',
    'StockPorDebajoDelMinimoException',
    'CategoriaVaciaException',
    'ProductoRepository',
]